version: '3.8'

services:

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: gestao-vendas-app:lates
    container_name: gestao_venda_app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - jaeger
      - prometheus
      - grafana
    command: ["-c", "/app/wait-for-mysql.sh mysql:3306 && java -jar /app/gestao_venda.jar"]
    entrypoint: ["/bin/sh"]

  mysql:
    image: mysql:8.2.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db


  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:7.4.1
    container_name: grafana
    ports: 
      - 3000:3000      