version: '3.8'

services:

  mysql:
    image: mysql:8.2.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db